
# Base URL
baseurl: /

# Site live URL
url: http://cohadar.github.io

# Localhost 
# url: http://127.0.0.1:4000  

# Conversion / Build settings 
markdown:    kramdown
# This is how you put pygments config in jekyll 2.0 instead of pygments: true
highlighter: pygments 

# Permalinks
permalink:        pretty

exclude: 
  - CNAME
  - README.md
  - .gitignore
